#!/usr/bin/env bash
# PostgreSQL helper for the nopCommerce Cloud Agent environment.
# Usage: pg.sh <ensure|start|is-seeded|write-appsettings>
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "${REPO_ROOT}/.cursor/env.sh"

PG_VERSION="$(nop_pg_version)"

start_cluster() {
    if ! sudo pg_lsclusters -h 2>/dev/null | awk '{print $4}' | grep -q online; then
        sudo pg_ctlcluster "${PG_VERSION}" main start >/dev/null 2>&1 || true
    fi
    # Wait for the server to accept connections.
    for _ in $(seq 1 30); do
        if sudo -u postgres pg_isready -q; then
            return 0
        fi
        sleep 1
    done
    echo "PostgreSQL did not become ready in time" >&2
    return 1
}

provision() {
    # Create the login role (idempotent).
    sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='${NOP_DB_USER}') THEN
    CREATE ROLE ${NOP_DB_USER} LOGIN PASSWORD '${NOP_DB_PASSWORD}' CREATEDB;
  END IF;
END \$\$;
SQL
    # Create the database (idempotent).
    if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${NOP_DB_NAME}'" | grep -q 1; then
        sudo -u postgres createdb -O "${NOP_DB_USER}" "${NOP_DB_NAME}"
    fi
    # nopCommerce's PostgreSQL provider requires these extensions.
    sudo -u postgres psql -d "${NOP_DB_NAME}" -v ON_ERROR_STOP=1 \
        -c "CREATE EXTENSION IF NOT EXISTS citext; CREATE EXTENSION IF NOT EXISTS pgcrypto;"
}

is_seeded() {
    PGPASSWORD="${NOP_DB_PASSWORD}" psql -h "${NOP_DB_HOST}" -p "${NOP_DB_PORT}" \
        -U "${NOP_DB_USER}" -d "${NOP_DB_NAME}" -tAc \
        "SELECT to_regclass('public.\"Product\"') IS NOT NULL AND (SELECT count(*) FROM \"Product\") > 0" 2>/dev/null \
        | grep -q '^t$'
}

write_appsettings() {
    # appsettings.json is git-ignored and regenerated by the app; nopCommerce merges
    # this file with defaults on startup, so supplying just the connection settings is
    # enough for it to recognise the database as installed.
    local app_data="${NOP_WEB_DIR}/App_Data"
    mkdir -p "${app_data}"
    local conn="Host=${NOP_DB_HOST};Port=${NOP_DB_PORT};Database=${NOP_DB_NAME};Username=${NOP_DB_USER};Password=${NOP_DB_PASSWORD}"
    cat > "${app_data}/appsettings.json" <<JSON
{
  "ConnectionStrings": {
    "ConnectionString": "${conn}",
    "DataProvider": "postgresql",
    "WithNoLock": false
  }
}
JSON
}

case "${1:-}" in
    start)            start_cluster ;;
    ensure)           start_cluster; provision ;;
    is-seeded)        is_seeded ;;
    write-appsettings) write_appsettings ;;
    *) echo "Usage: $0 <ensure|start|is-seeded|write-appsettings>" >&2; exit 2 ;;
esac
